### ISSUE TITLE
Plot waypoints on google maps

### ISSUE THREAD

**Issue by lo9key** [LBCC-SpaceClub/HAB-Summer-2015#1]
We should plot these waypoints on a map, which I think we can do using the pygmaps library.

Need to look into how well this works with no internet connection.

We should decide how to handle invalid callsigns.

Loading previous runs from log files would be good, too.

**Comment by lo9key** [comment]
There are lots of ways to plot these points on a map.

One of the more common suggestions I've seen is to use pygmaps, however it has some flaws.  I started a branch called '[pygmaps](https://github.com/LBCC-SpaceClub/HAB-Summer-2015/tree/pygmaps)' to experiment with this library, although I suspect it's dependancy on an internet connection means it won't be useful for us.

**Comment by lwillmeth** [comment]
We began using YAAC instead of pygmaps.
